name: Unit Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"

    - name: Set PYTHONPATH
      run: |
        echo "PYTHONPATH=$(pwd)" >> $GITHUB_ENV
    - name: Test with unittest
      run: |
        pip install concurrent-log-handler
        python -m unittest discover -s tests -p "*.py"        

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ruff
    - name: Run Ruff
      run: ruff check .
